### ISSUE TITLE
Not able to run cluster.

### ISSUE THREAD

**Issue by mbtamuli** [autopilotpattern/mysql#99]
When doing `docker-compose up`, this error shows up in the logs
```
mysql_1   | 2017/12/03 22:47:20 check.mysql.Run start
mysql_1   | 2017/12/03 22:47:21 Traceback (most recent call last):
mysql_1   | 2017/12/03 22:47:21   File "/usr/local/bin/manage.py", line 407, in <module>
mysql_1   | 2017/12/03 22:47:21     main()
mysql_1   | 2017/12/03 22:47:21   File "/usr/local/bin/manage.py", line 399, in main
mysql_1   | 2017/12/03 22:47:21     manta = Manta()
mysql_1   | 2017/12/03 22:47:21   File "/usr/local/bin/manager/libmanta.py", line 36, in __init__
mysql_1   | 2017/12/03 22:47:21     signer=self.signer)
mysql_1   | 2017/12/03 22:47:21   File "/usr/local/lib/python2.7/dist-packages/manta/client.py", line 140, in __init__
mysql_1   | 2017/12/03 22:47:21     assert account, 'account'
mysql_1   | 2017/12/03 22:47:21 AssertionError: account
mysql_1   | 2017/12/03 22:47:21 check.mysql exited with error: check.mysql: exit status 1
mysql_1   | 2017/12/03 22:47:21 event: {ExitFailed check.mysql}
mysql_1   | 2017/12/03 22:47:21 event: {Error check.mysql: exit status 1}
mysql_1   | 2017/12/03 22:47:21 check.mysql.Run end
mysql_1   | 2017/12/03 22:47:21 check.mysql.kill
mysql_1   | 2017/12/03 22:47:21 killing command 'check.mysql' at pid: 378
mysql_1   | 2017/12/03 22:47:21 event: {StatusUnhealthy mysql}
```

When I tried running the tests(`./tests/compose.sh`), they too failed. Here are the [logs](https://gist.github.com/mbtamuli/9391338cefeb00ff9772543723d977f3)

**Comment by dfredell** [comment]
It looks like it can't connect to Manta, that you are missing the `MANTA_USER` env. Did you run examples/triton/client.py that generates a _env file?

O I see from your other log that you are trying to use minio. Note that the latest docker build on dockerhub doesn't include the minio code. You will have to build the docker locally.

**Comment by benyanke** [comment]
I'm getting this as well, with the example minio config:

```yaml
version: '2.1'

services:
  mysql:
    image: autopilotpattern/mysql:${TAG:-latest}
    mem_limit: 512m
    restart: always
    expose:
      - 3306
    network_mode: bridge
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=seekretPassword
      - MYSQL_REPL_USER=repluser
      - MYSQL_REPL_PASSWORD=seekretReplPassword
      - MYSQL_DATABASE=demodb
      - BACKUP_TTL=120
      - LOG_LEVEL=DEBUG
      - CONSUL=consul
      - SNAPSHOT_BACKEND=minio
      - MINIO_ACCESS_KEY=supersecretaccesskey
      - MINIO_SECRET_KEY=supersecretsecretkey
    volumes:
      # shared storage location for snapshots
      - ${WORK_DIR:-../..}/tmp:/tmp/snapshots
    links:
      - consul:consul
      - minio:minio

  consul:
    image: consul:0.8.4
    command: >
      agent -server -client=0.0.0.0 -dev -ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    network_mode: bridge
    dns:
      - 127.0.0.1

  minio:
    image: minio/minio
    command: server /export
    restart: always
    expose:
      - 9000
    network_mode: bridge
    environment:
      - MINIO_ACCESS_KEY=supersecretaccesskey
      - MINIO_SECRET_KEY=supersecretsecretkey





```
